name: DistancePlaceholder
version: '${version}'
main: ru.iamdvz.distanceplaceholder.DistancePlaceholder
api-version: 1.16
depend: [ PlaceholderAPI ]
authors: [ iamDvz ]
description: distance placeholder
website: iamDvz.ru
commands:
  distancepl:
    aliases: [distancepl]
    description: Distancepl command

permissions:
  distanceplaceholder.admin:
    description: needed for admin commands
    default: op